// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9meOMA78ZsdsIQ4Ow8vcDvDY0nzDlAA',
    appId: '1:121380918902:web:813a69f3e8f979d6d7f157',
    messagingSenderId: '121380918902',
    projectId: 'gemailai-39acf',
    authDomain: 'gemailai-39acf.firebaseapp.com',
    storageBucket: 'gemailai-39acf.appspot.com',
    measurementId: 'G-WWNY425529',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9meOMA78ZsdsIQ4Ow8vcDvDY0nzDlAA',
    appId: '1:121380918902:android:b58ee543b9c51caad7f157',
    messagingSenderId: '121380918902',
    projectId: 'gemailai-39acf',
    storageBucket: 'gemailai-39acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADpEiMiLbMyxehUp-FRhVKv9xls2XnceE',
    appId: '1:121380918902:ios:e42e2ef7e52fcc17d7f157',
    messagingSenderId: '121380918902',
    projectId: 'gemailai-39acf',
    storageBucket: 'gemailai-39acf.appspot.com',
    androidClientId: '121380918902-22kachjbv25lkh69tqp46poff58k5tlb.apps.googleusercontent.com',
    iosClientId: '121380918902-r22p5rk8mujoasircnqtn15754ma05cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemailai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADpEiMiLbMyxehUp-FRhVKv9xls2XnceE',
    appId: '1:121380918902:ios:e42e2ef7e52fcc17d7f157',
    messagingSenderId: '121380918902',
    projectId: 'gemailai-39acf',
    storageBucket: 'gemailai-39acf.appspot.com',
    androidClientId: '121380918902-22kachjbv25lkh69tqp46poff58k5tlb.apps.googleusercontent.com',
    iosClientId: '121380918902-r22p5rk8mujoasircnqtn15754ma05cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemailai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK9meOMA78ZsdsIQ4Ow8vcDvDY0nzDlAA',
    appId: '1:121380918902:web:f169cfa5e7e33899d7f157',
    messagingSenderId: '121380918902',
    projectId: 'gemailai-39acf',
    authDomain: 'gemailai-39acf.firebaseapp.com',
    storageBucket: 'gemailai-39acf.appspot.com',
    measurementId: 'G-KH5RWK2L95',
  );
}
